# Generated by Django 4.1.7 on 2023-07-20 02:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsanAdong5179',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=5179)),
                ('objectid', models.BigIntegerField(blank=True, null=True)),
                ('adm_nm', models.CharField(blank=True, max_length=80, null=True)),
                ('adm_cd', models.CharField(blank=True, max_length=80, null=True)),
                ('adm_cd2', models.CharField(blank=True, max_length=80, null=True)),
                ('sgg', models.CharField(blank=True, max_length=80, null=True)),
                ('sido', models.CharField(blank=True, max_length=80, null=True)),
                ('sidonm', models.CharField(blank=True, max_length=80, null=True)),
                ('temp', models.CharField(blank=True, max_length=80, null=True)),
                ('sggnm', models.CharField(blank=True, max_length=80, null=True)),
                ('adm_cd8', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'Asan_adong_5179',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsanGridPop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=5179)),
                ('gid', models.CharField(blank=True, max_length=254, null=True)),
                ('lbl', models.CharField(blank=True, max_length=254, null=True)),
                ('val', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'Asan_grid_pop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsanSlib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=5179)),
                ('도서관명', models.CharField(blank=True, max_length=254, null=True)),
                ('주소', models.CharField(blank=True, max_length=254, null=True)),
                ('x', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'Asan_SLib',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AdminSgg',
        ),
        migrations.DeleteModel(
            name='AdminSid',
        ),
        migrations.DeleteModel(
            name='ba_g_2001',
        ),
        migrations.DeleteModel(
            name='BlockGeometry',
        ),
        migrations.DeleteModel(
            name='BlockText',
        ),
        migrations.DeleteModel(
            name='Stores',
        ),
    ]
