# Generated by Django 4.1.7 on 2023-08-07 08:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_asanaccessibility_alter_asanadong5179_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsanGrid500M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=5179)),
                ('gid', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'asan_grid_500m',
                'managed': False,
            },
        ),
    ]
