# Generated by Django 4.1.7 on 2023-10-06 08:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_asangrid500m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asanemdpop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=5179)),
                ('adm_nm', models.CharField(blank=True, max_length=80, null=True)),
                ('adm_cd', models.CharField(blank=True, max_length=80, null=True)),
                ('adm_cd2', models.CharField(blank=True, max_length=80, null=True)),
                ('sgg', models.CharField(blank=True, max_length=80, null=True)),
                ('sido', models.CharField(blank=True, max_length=80, null=True)),
                ('sidonm', models.CharField(blank=True, max_length=80, null=True)),
                ('temp', models.CharField(blank=True, max_length=80, null=True)),
                ('sggnm', models.CharField(blank=True, max_length=80, null=True)),
                ('adm_cd8', models.CharField(blank=True, max_length=80, null=True)),
                ('총인구', models.CharField(blank=True, max_length=80, null=True)),
                ('유아', models.CharField(blank=True, max_length=80, null=True)),
                ('초등학생', models.CharField(blank=True, max_length=80, null=True)),
                ('중학생', models.CharField(blank=True, max_length=80, null=True)),
                ('고등학생', models.CharField(blank=True, max_length=80, null=True)),
                ('성인', models.CharField(blank=True, max_length=80, null=True)),
                ('생산가능', models.CharField(blank=True, max_length=80, null=True)),
                ('노인', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'AsanEmdPop',
                'managed': False,
            },
        ),
    ]
