# Generated by Django 4.1.7 on 2023-10-06 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_asanemdpop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asanemdpop',
            table='asanEmdPop',
        ),
    ]
