# Generated by Django 4.2.5 on 2023-10-16 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_asanemdpop_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsanAccessibility',
        ),
        migrations.DeleteModel(
            name='Asanemdpop',
        ),
        migrations.AlterModelTable(
            name='asanadong5179',
            table='Asan_adong_5179',
        ),
        migrations.AlterModelTable(
            name='asangridpop',
            table='Asan_grid_pop',
        ),
        migrations.AlterModelTable(
            name='asanslib',
            table='Asan_SLib',
        ),
    ]
