# Generated by Django 4.2.5 on 2023-10-16 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_asanemdpop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asanemdpop',
            table='asan_emd_pop',
        ),
    ]
