# Generated by Django 4.2.5 on 2023-10-16 06:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_alter_asanemdpop_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='천안아산시_SOC',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=5179)),
                ('id_0', models.BigIntegerField(blank=True, null=True)),
                ('sgg_nm_k', models.CharField(blank=True, max_length=80, null=True)),
                ('sgg_cd', models.CharField(blank=True, max_length=80, null=True)),
                ('sido_nm_k', models.CharField(blank=True, max_length=80, null=True)),
                ('sido_cd', models.CharField(blank=True, max_length=80, null=True)),
                ('fac_nm', models.CharField(blank=True, max_length=80, null=True)),
                ('fac_add', models.CharField(blank=True, max_length=174, null=True)),
                ('emd_nm', models.CharField(blank=True, max_length=80, null=True)),
                ('type', models.CharField(blank=True, max_length=80, null=True)),
                ('x', models.CharField(blank=True, max_length=80, null=True)),
                ('y', models.CharField(blank=True, max_length=80, null=True)),
                ('layer', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': '천안아산시_SOC',
                'managed': False,
            },
        ),
    ]
