# Generated by Django 4.2.5 on 2023-10-27 01:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_천안아산시_soc'),
    ]

    operations = [
        migrations.CreateModel(
            name='경관지구_아산시_5179',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=5179)),
                ('alias', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('ntfdate', models.CharField(blank=True, max_length=8, null=True)),
                ('col_adm_se', models.CharField(blank=True, max_length=5, null=True)),
                ('sgg_oid', models.IntegerField(blank=True, null=True)),
                ('mnum', models.CharField(blank=True, max_length=33, null=True)),
            ],
            options={
                'db_table': '경관지구_아산시_5179',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='국토계획_아산시_5179',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=5179)),
                ('col_adm_se', models.CharField(blank=True, max_length=5, null=True)),
                ('sgg_oid', models.IntegerField(blank=True, null=True)),
                ('mnum', models.CharField(blank=True, max_length=33, null=True)),
                ('alias', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('ntfdate', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': '국토계획_아산시_5179',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='도시지역_아산시_5179',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=5179)),
                ('mnum', models.CharField(blank=True, max_length=33, null=True)),
                ('sgg_oid', models.IntegerField(blank=True, null=True)),
                ('col_adm_se', models.CharField(blank=True, max_length=5, null=True)),
                ('ntfdate', models.CharField(blank=True, max_length=8, null=True)),
                ('alias', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': '도시지역_아산시_5179',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='지적_아산시_5179',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=5179)),
                ('sgg_oid', models.BigIntegerField(blank=True, null=True)),
                ('jibun', models.CharField(blank=True, max_length=100, null=True)),
                ('bchk', models.CharField(blank=True, max_length=1, null=True)),
                ('pnu', models.CharField(blank=True, max_length=19, null=True)),
                ('col_adm_se', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': '지적_아산시_5179',
                'managed': False,
            },
        ),
    ]
