# Generated by Django 4.2.5 on 2023-10-27 10:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_경관지구_분류_아산_5179_국토계획_분류_아산_5179_도시지역_분류_아산_5179_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='아산시500M인구',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=5179)),
                ('gid', models.CharField(blank=True, max_length=254, null=True)),
                ('lbl', models.CharField(blank=True, max_length=254, null=True)),
                ('val', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': '아산_500m_1',
                'managed': False,
            },
        ),
    ]
